/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.saikrishna.reactive.learning;

import com.github.javafaker.Faker;
import reactor.core.publisher.Flux;

public class App {

    public static void main(String[] args) {

        Flux.range(1,10).map(integer -> Faker.instance().name().fullName()).subscribe(System.out::println);
    }
}
