/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.saikrishna.reactive.learning;

import reactor.core.publisher.Flux;

public class App {

    public static void main(String[] args) {

        System.out.println("Hello World!");
    }
}
